version: "3.7"

services:
  redis:
    image: redis:5.0.7-alpine
    container_name: meeting_redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:12.2
    container_name: meeting_postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: roombelt
    ports:
      - "5432:5432"
